### ISSUE TITLE
Error: Duplicate identifier

### ISSUE THREAD

**Issue by MickL** [sanchezzzhak/node-device-detector#118]
Getting multiple errors with the latest version:

> node_modules/node-device-detector/index.d.ts:32:9 - error TS2300: Duplicate identifier 'deviceIndexes'.
> node_modules/node-device-detector/index.d.ts:33:9 - error TS2300: Duplicate identifier 'deviceIndexes'.
> node_modules/node-device-detector/index.d.ts:34:9 - error TS2300: Duplicate identifier 'deviceAliasCode'.
> node_modules/node-device-detector/index.d.ts:35:9 - error TS2300: Duplicate identifier 'deviceAliasCode'.
> node_modules/node-device-detector/index.d.ts:42:9 - error TS2300: Duplicate identifier 'deviceIndexes'.
> node_modules/node-device-detector/index.d.ts:47:9 - error TS2300: Duplicate identifier 'deviceIndexes'.
> node_modules/node-device-detector/index.d.ts:52:9 - error TS2300: Duplicate identifier 'deviceAliasCode'.
> node_modules/node-device-detector/index.d.ts:57:9 - error TS2300: Duplicate identifier 'deviceAliasCode'.

Was working in 2.0.5 but not with 2.0.6, 2.0.7 and 2.0.8

**Comment by sanchezzzhak** [comment]
* I fixed it,  this changes will be available in 2.0.9 tomorrow or 1-2 days later.
